# Generated by Django 3.2.9 on 2021-11-04 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyparticipation',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='question',
            name='dependency_answer_option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_dependent_on_answer_option', to='surveys.answeroption', verbose_name="This question's Answer Option dependency"),
        ),
        migrations.AddField(
            model_name='question',
            name='dependency_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_dependent_on_question', to='surveys.question', verbose_name="This question's Question dependency"),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveysection', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='surveys.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='have_chosen_this_option', to='surveys.answeroption'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='survey_participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_of_survey_participation', to='surveys.surveyparticipation'),
        ),
        migrations.AddConstraint(
            model_name='surveyparticipation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user_account__isnull', True), ('user_session__isnull', False)), models.Q(('user_account__isnull', False), ('user_session__isnull', True)), _connector='OR'), name='api_surveyparticipation_useraccount_or_usersession'),
        ),
    ]
